// File generated by flutterfire_cli.
// This is a placeholder file. Replace with actual Firebase config.
// Run: flutterfire configure
// Or manually update the FirebaseOptions below.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:web:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'sfx-legacy-vault',
    authDomain: 'sfx-legacy-vault.firebaseapp.com',
    storageBucket: 'sfx-legacy-vault.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'sfx-legacy-vault',
    storageBucket: 'sfx-legacy-vault.appspot.com',
    iosBundleId: 'com.sfx.sfxLegacyVault',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:android:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'sfx-legacy-vault',
    storageBucket: 'sfx-legacy-vault.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:web:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'sfx-legacy-vault',
    authDomain: 'sfx-legacy-vault.firebaseapp.com',
    storageBucket: 'sfx-legacy-vault.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'sfx-legacy-vault',
    storageBucket: 'sfx-legacy-vault.appspot.com',
    iosBundleId: 'com.sfx.sfxLegacyVault',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:web:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'sfx-legacy-vault',
    authDomain: 'sfx-legacy-vault.firebaseapp.com',
    storageBucket: 'sfx-legacy-vault.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
